# Generated by Django 5.2.8 on 2025-11-10 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nmae',
            new_name='name',
        ),
    ]
